language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
gemfile:
  - gemfiles/Gemfile.rails-3.0
  - gemfiles/Gemfile.rails-3.1
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-edge
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.3.0
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.3.1
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-edge
  allow_failures:
    - rvm: ruby-head
